version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=2048"
    NPM_CONFIG_MAXSOCKETS: "1"
    NPM_CONFIG_PROGRESS: "false"
    NPM_CONFIG_FUND: "false"
    NPM_CONFIG_AUDIT: "false"
    NPM_CONFIG_LOGLEVEL: "error"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing backend dependencies..."
      - npm --version
      - node --version
      - cd backend/api
      - npm ci --no-optional --no-fund --no-audit --prefer-offline || exit 1
      - cd ../..
  
  pre_build:
    commands:
      - echo "Running backend tests..."
      - cd backend/api
      - npm run test || exit 1
      - cd ../..
      
  build:
    commands:
      - echo "Building backend application..."
      - cd backend/api
      - npm run build || exit 1
      - echo "Verifying build artifacts..."
      - ls -la dist/ || echo "Backend dist folder not found"
      - cd ../..
      
  post_build:
    commands:
      - echo "Backend build completed successfully"
      - echo "Clearing any error flags..."
      - unset CodePipeline_ErrorCode
      - unset CodePipeline_ErrorSummary

artifacts:
  files:
    - 'backend/api/dist/**/*'
    - 'backend/api/package.json'
    - 'backend/api/package-lock.json'
  name: contextmd-backend-$(date +%Y-%m-%d)

cache:
  paths:
    - backend/api/node_modules/**/*
