version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - pwd
      - ls -la
      - find . -name "backend" -type d
      - find . -name "*.json" | head -10
      - npm --prefix backend/api install
      
  build:
    commands:
      - echo "Building backend"
      - npm --prefix backend/api run build
      - ls -la backend/api/dist/

artifacts:
  files:
    - 'backend/api/dist/**/*'
    - 'backend/api/package.json'
