version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm --version
      - node --version
      - npm ci
      - npm run install:all
  
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      - echo "Checking environment variables..."
      
  build:
    commands:
      - echo "Building the application..."
      - npm run build
      
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  name: contextmd-build-$(date +%Y-%m-%d)

cache:
  paths:
    - node_modules/**/*
    - frontend/node_modules/**/*
    - backend/api/node_modules/**/*
