version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - cd backend/api
      - npm install
      
  build:
    commands:
      - echo "Building backend"
      - cd backend/api
      - npx tsc -p tsconfig.json
      - ls -la dist/

artifacts:
  files:
    - 'backend/api/dist/**/*'
    - 'backend/api/package.json'
