version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=1024"
    NPM_CONFIG_MAXSOCKETS: "1"
    NPM_CONFIG_PROGRESS: "false"
    NPM_CONFIG_FUND: "false"
    NPM_CONFIG_AUDIT: "false"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies with memory optimization..."
      - npm --version
      - node --version
      - echo "Installing backend dependencies first..."
      - cd backend/api
      - npm ci --no-optional --no-fund --no-audit --prefer-offline || exit 1
      - cd ../..
      - echo "Installing frontend dependencies..."
      - cd frontend  
      - npm ci --no-optional --no-fund --no-audit --prefer-offline || exit 1
      - cd ..
  
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      - echo "Checking environment variables..."
      - npm run test || exit 1
      
  build:
    commands:
      - echo "Building the application..."
      - npm run build || exit 1
      - echo "Verifying build artifacts..."
      - ls -la backend/api/dist/ || echo "Backend dist folder not found"
      - ls -la frontend/build/ || echo "Frontend build folder not found"
      
  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Clearing any error flags..."
      - unset CodePipeline_ErrorCode
      - unset CodePipeline_ErrorSummary

artifacts:
  files:
    - 'backend/api/dist/**/*'
    - 'frontend/build/**/*'
    - 'package.json'
    - 'buildspec.yml'
  name: contextmd-build-$(date +%Y-%m-%d)

cache:
  paths:
    - node_modules/**/*
    - frontend/node_modules/**/*
    - backend/api/node_modules/**/*
